import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

// Load .env file if exists
function loadEnv() {
	const envPath = resolve(process.cwd(), '.env');
	if (!existsSync(envPath)) return {};

	const env = {};
	const content = readFileSync(envPath, 'utf-8');
	for (const line of content.split('\n')) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith('#')) continue;
		const [key, ...valueParts] = trimmed.split('=');
		if (key) env[key.trim()] = valueParts.join('=').trim();
	}
	return env;
}

const env = loadEnv();
const pluginDir = env.OBSIDIAN_PLUGIN_DIR;

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: (!prod && pluginDir) ? `${pluginDir}/main.js` : "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	if (pluginDir) {
		console.log(`[dev] Output to: ${pluginDir}/main.js`);
	} else {
		console.log("[dev] OBSIDIAN_PLUGIN_DIR not set. Output to: ./main.js");
		console.log("[dev] Create .env file with OBSIDIAN_PLUGIN_DIR to enable direct vault output.");
	}
	await context.watch();
}
